version: '3.7'

services:
  dev:
    image: ${DOCKER_REGISTRY-}nugetrepackdev
    container_name: nugetrepackdev
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ADDITIONAL_SDK_VERSIONS=3.0.100-preview7-012821
        - ADDITIONAL_SDK_CHECKSUMS=DF70CA86453CEBA51B480BC8521D6BF76625469CDD3DA6FE782B85F13620D8BEEB34E02EE7AFE2803CD144066E7C685E5A1A9A4005ADC9B2709C69F7F37C9BDC
        - CONTAINER_USERNAME=${CONTAINER_USERNAME:-dev}
        - CONTAINER_UID=${CONTAINER_UID:-1000}
        - CONTAINER_GID=${CONTAINER_GID:-1000}

    volumes:
      # this is the main workspace mount
      - ..:/src
      # this lets you avoid setting up Git again
      - ~/.gitconfig:/home/${CONTAINER_USERNAME}/.gitconfig
      # this allows Git to use your SSH keys
      - ~/.ssh:/home/${CONTAINER_USERNAME}/.ssh-localhost:ro
      # access host configured nuget feeds and package cache
      - ~/.nuget:/home/${CONTAINER_USERNAME}/.nuget

    environment:
      - PUSH_SOURCE
      - PUSH_APIKEY

    # overrides default command so things don't shut down after the process ends
    command: sleep infinity
