version: '3.7'

services:
  dev:
    image: ${DOCKER_REGISTRY-}nugetrepackdev
    container_name: nugetrepackdev
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ADDITIONAL_SDK_VERSIONS=3.0.100
        - ADDITIONAL_SDK_CHECKSUMS=766da31f9a0bcfbf0f12c91ea68354eb509ac2111879d55b656f19299c6ea1c005d31460dac7c2a4ef82b3edfea30232c82ba301fb52c0ff268d3e3a1b73d8f7
        - CONTAINER_USERNAME=${CONTAINER_USERNAME:-dev}
        - CONTAINER_UID=${CONTAINER_UID:-1000}
        - CONTAINER_GID=${CONTAINER_GID:-1000}

    volumes:
      # this is the main workspace mount
      - ..:/src
      # this lets you avoid setting up Git again
      - ~/.gitconfig:/home/${CONTAINER_USERNAME}/.gitconfig
      # this allows Git to use your SSH keys
      - ~/.ssh:/home/${CONTAINER_USERNAME}/.ssh-localhost:ro
      # access host configured nuget feeds and package cache
      - ~/.nuget:/home/${CONTAINER_USERNAME}/.nuget

    environment:
      - PUSH_SOURCE
      - PUSH_APIKEY

    # overrides default command so things don't shut down after the process ends
    command: sleep infinity
